#!/bin/sh
mvn clean package && docker build -t maryamshaikh/MSASecondApp .
docker rm -f MSASecondApp 2>/dev/null || true && docker run -it --name MSASecondApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSASecondApp maryamshaikh/MSASecondApp
